Update / Add build and runtime configuration files
unikraft/app-helloworld pull request #22
Opened 2023-08-03 20:56 UTC by razvand

Update QEMU and Firecraker build and runtime configuration files.

2023-08-05 14:01 UTC, RaduNichita requested changes
It looks very good, @razvand ! I left some minor nitpicks.

Furthermore, I have a question. When running on firecracker, I see some strange arguments:

```text
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
                  Atlas 0.13.1~325daa41
Hello world!
Arguments:  "reboot=k" "panic=1" "pci=off" "nomodules" "8250.nr_uarts=0" "i8042.noaux" "i8042.nomux" "i8042.nopnp" "i8042.dumbkbd"
```

Should we display those? I don't know if they are related to Unikraft.

2023-08-05 14:01 UTC, RaduNichita commented on .config.helloworld-qemu-aarch64
Please update the README to fit this change.

2023-08-05 14:01 UTC, RaduNichita commented on .config.helloworld-qemu-x86_64
Please update the README to fit this change.

2023-08-05 14:01 UTC, RaduNichita commented on .config.helloworld-fc-x86_64
Please update the README with instructions to build / run the application using firecracker.

2023-08-06 08:17 UTC, razvand commented
> Should we display those? I don't know if they are related to Unikraft.

I think they are related to Firecracker, so I chose not to display them.

2023-08-06 16:26 UTC, RaduNichita approved these changes
All good from my side now. Thanks @razvand 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-06 17:17 UTC, StefanJum approved these changes
All good, thanks.

Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-09 10:23 UTC, closed without merging