Stefan jum/add dev content
unikraft/app-helloworld pull request #25
Opened 2023-09-23 00:34 UTC by StefanJum

2023-09-24 14:12 UTC, razvand commented
Please also add an update to the `README.md` file. See the updates from [this commit](https://github.com/unikraft/app-elfloader/commit/450a52101b17ed041ae97b9d219c997669309cdf).

2023-09-26 14:31 UTC, StefanJum commented
Done @razvand

2023-09-30 17:31 UTC, razvand requested changes
Remove the `generate.py` script, since it's now downloaded. Also ignore it.

2023-09-30 17:31 UTC, razvand commented on README.md
> +To make it easier build and run and test different configurations, the repository provides a set of scripts that do everything required.
```suggestion
To make it easier to build, run and test different configurations, the repository provides a set of scripts that do everything required.
```

2023-09-30 17:31 UTC, razvand commented on README.md
> +First, generate these scripts by running the `generate.py` script while on the `helloworld` directory:
```suggestion
First of all, grab the [`generate.py` script](https://github.com/unikraft/app-testing/blob/staging/scripts/generate.py) and place it in the `scripts/` directory by running:

'''console
wget https://raw.githubusercontent.com/unikraft/app-testing/staging/scripts/generate.py -O scripts/generate.py
chmod a+x scripts/generate.py
'''

Now, run the `generate.py` script.
You must run it in the root directory of this repository:
```

Replace the apostrophes above with backticks.

2023-09-30 17:33 UTC, razvand commented
Also replace the TLDR with the downloading and using of `generate.py`, same a documented [here](https://github.com/unikraft/app-llama2-c/#quick-set-up-aka-tldr).

2023-10-03 19:18 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-10-03 19:18 UTC, merged