README.md: Update the way `kraft up` is run
unikraft/app-helloworld pull request #3
Opened 2021-09-10 10:00 UTC by mogasergiu

Change the way `kraft up` is run, as now the `-t` option seems to be mandatory.

2021-10-13 20:41 UTC, gabrielmocanu requested changes
I think it's easier to put \ there too, so that anyone can give a copy-paste.

2021-10-13 20:41 UTC, gabrielmocanu commented on README.md
> +                        -enable-kvm
```suggestion
                        -enable-kvm \
```

2021-11-09 22:56 UTC, gabrielmocanu approved these changes
All good right now.

Reviewed-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

2021-11-27 14:02 UTC, razvand commented
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2021-11-27 19:15 UTC, closed without merging